mysql:
  image: percona:5.6
  ports: ["127.0.0.1:3306:3306"]
  environment:
    MYSQL_ROOT_PASSWORD: "password"

redis:
  image: redis:latest
  ports:
    - "127.0.0.1:6379:6379"

memcached:
  image: memcached:latest
  ports:
    - "127.0.0.1:11211:11211"
